name: class_track
description: Student class trip attendance app
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0

flutter:
  uses-material-design: true
